blueprint:
  name: Update Tomorrow Workday Status
  description: >
    Check if tomorrow is a workday or school day and update the specified input boolean accordingly.
    Runs at a specified time daily to check if tomorrow is a workday based on selected workday sensors.
  domain: automation
  input:
    workday_sensors:
      name: Workday Binary Sensors
      description: >
        Select one or more binary sensors that indicate workday status.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    schoolday_sensors:
      name: School Day Binary Sensors
      description: >
        Select one or more binary sensors that indicate school day status.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    output_boolean:
      name: Output Input Boolean
      description: >
        The input boolean to turn on/off based on the check.
      selector:
        entity:
          domain: input_boolean
    trigger_time:
      name: Trigger Time
      description: >
        Time to run the automation (HH:MM:SS format).
      selector:
        time: {}
      default: "00:01:00"

  source_url: https://github.com/rubicon/rubicon-ha-tomorrow-workday-blueprint
  homeassistant:
    min_version: "2023.7.0"

mode: single

trigger:
  - platform: time
    at: !input trigger_time

variables:
  tomorrow_date: "{{ (now() + timedelta(days=1)).date() }}"
  workday_sensors: !input workday_sensors
  schoolday_sensors: !input schoolday_sensors

action:
  # Check all workday sensors
  - repeat:
      for_each: "{{ workday_sensors }}"
      sequence:
        - service: workday.check_date
          target:
            entity_id: "{{ repeat.item }}"
          data:
            check_date: "{{ tomorrow_date }}"
          response_variable: "workday_check_{{ repeat.index }}"

  # Check all schoolday sensors
  - repeat:
      for_each: "{{ schoolday_sensors }}"
      sequence:
        - service: workday.check_date
          target:
            entity_id: "{{ repeat.item }}"
          data:
            check_date: "{{ tomorrow_date }}"
          response_variable: "schoolday_check_{{ repeat.index }}"

  # Aggregate results and update output boolean
  - variables:
      # Check if any workday sensor indicates tomorrow is a workday
      any_workday: >
        {% set ns = namespace(is_workday=false) %}
        {% for i in range(workday_sensors | length) %}
          {% set var_name = 'workday_check_' ~ (i + 1) %}
          {% if var_name in _context %}
            {% set sensor_id = workday_sensors[i] %}
            {% if _context[var_name].get(sensor_id, {}).get('workday', false) %}
              {% set ns.is_workday = true %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {% for i in range(schoolday_sensors | length) %}
          {% set var_name = 'schoolday_check_' ~ (i + 1) %}
          {% if var_name in _context %}
            {% set sensor_id = schoolday_sensors[i] %}
            {% if _context[var_name].get(sensor_id, {}).get('workday', false) %}
              {% set ns.is_workday = true %}
            {% endif %}
          {% endif %}
        {% endfor %}
        {{ ns.is_workday }}

  - service: "input_boolean.turn_{{ 'on' if any_workday else 'off' }}"
    target:
      entity_id: !input output_boolean
